# Generated by Django 4.2.9 on 2024-01-23 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("backend_internal_app2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualities",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="create_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
