# Generated by Django 4.2.9 on 2024-01-24 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend_internal_app2", "0002_qualities_date_updated_alter_qualities_create_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualities",
            name="capacity_for_change",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)],
            ),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="client_relations",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)],
            ),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="communication",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)],
            ),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="conceptual_design_ability",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)],
            ),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="honesty_integrity",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)],
            ),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="independent_work",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)],
            ),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="problem_solving_ability",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)],
            ),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="productivity",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)],
            ),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="professional_appearance",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)],
            ),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="punctuality_attendance",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)],
            ),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="quality_of_work",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)],
            ),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="sense_of_responsibility",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)],
            ),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="strategic_perspective",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)],
            ),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="takes_initiative",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)],
            ),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="team_work",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)],
            ),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="technical_programming_skills",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)],
            ),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="work_consistency",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)],
            ),
        ),
    ]
