# Generated by Django 4.2.9 on 2024-02-15 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend_internal_app2", "0003_alter_qualities_capacity_for_change_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualities",
            name="capacity_for_change",
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="client_relations",
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="communication",
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="conceptual_design_ability",
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="honesty_integrity",
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="independent_work",
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="problem_solving_ability",
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="productivity",
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="professional_appearance",
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="punctuality_attendance",
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="quality_of_work",
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="sense_of_responsibility",
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="strategic_perspective",
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="takes_initiative",
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="team_work",
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="technical_programming_skills",
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name="qualities",
            name="work_consistency",
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
    ]
