# Generated by Django 4.2.9 on 2024-02-19 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend_internal_app2", "0005_score"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Score",
        ),
    ]
