# Generated by Django 4.2.9 on 2024-02-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0010_employee_alter_attendance_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="date_added",
            field=models.DateTimeField(null=True),
        ),
    ]
