# Generated by Django 4.2.9 on 2024-02-12 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0012_alter_course_date_added"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="assigned_faculty",
        ),
        migrations.RemoveField(
            model_name="classstudent",
            name="classIns",
        ),
        migrations.RemoveField(
            model_name="classstudent",
            name="student",
        ),
        migrations.RemoveField(
            model_name="course",
            name="department",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="course",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="department",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Attendance",
        ),
        migrations.DeleteModel(
            name="Class",
        ),
        migrations.DeleteModel(
            name="ClassStudent",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
