# Generated by Django 4.2.9 on 2024-02-12 11:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("attendance", "0013_remove_class_assigned_faculty_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True, null=True)),
                ("status", models.IntegerField(default=1)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True, null=True)),
                ("status", models.IntegerField(default=1)),
                ("date_added", models.DateTimeField(blank=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="attendance.department"),
                ),
            ],
        ),
    ]
